version: "3.3"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
      

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    depends_on:
      - db
